### ISSUE TITLE
Adding IPMI ip/mac

### ISSUE THREAD

**Issue by svennd** [arjitc/DCIMStack#14]
Would be nice if there was a feature IPMI device option to add IP/MAC.

**Comment by arjitc** [comment]
Yup, this is planned for. When the server(s) are added into DCIMStack, I'll add a option to add IPMI details as well.

**Comment by arjitc** [comment]
![image](https://cloud.githubusercontent.com/assets/363587/13287769/a747d9d2-db2e-11e5-8333-65eb889cb00d.png)

Done :) this has been added
