### ISSUE TITLE
how to use the libreNMS api

### ISSUE THREAD

**Issue by svennd** [arjitc/DCIMStack#46]
How to use the libreNMS api ? a tutorial would be highly appreciated, great software btw, looks nice !

**Comment by arjitc** [comment]
Work in progress on this, it works but there's no frontend way to add the graphs for a port (it can be done via the editing DB manually though). Working on the configure port setting at the moment which should allow for this to be done via the frontend UI itself :)

**Comment by arjitc** [comment]
Added the basic documentation on this, https://github.com/arjitc/DCIMStack/wiki/DCIMStack-Settings for the initial API key and API end-point, working on adding/configuring the graphs now.

**Comment by arjitc** [comment]
Added now :smile: 
1. Add a network device to a rack
2. Click on any of the ports and you'll be able to configure the Port Label (can be anything) and the Port Name (should match LibreNMS port)

Eg: 

![image](https://cloud.githubusercontent.com/assets/363587/13748502/1cdf9448-ea23-11e5-8416-7047f960dbf8.png)

![image](https://cloud.githubusercontent.com/assets/363587/13748427/d229a8ee-ea22-11e5-863e-ad5f16410ee4.png)

![image](https://cloud.githubusercontent.com/assets/363587/13748519/2643b55a-ea23-11e5-9404-9b1deaddd8e6.png)

**Comment by arjitc** [comment]
Added to https://github.com/arjitc/DCIMStack/wiki/Rackspace-Network-Ports-(from-LibreNMS) as well
